### ISSUE TITLE
ldpred2 questions - adjusted beta values + scaling + prediction

### ISSUE THREAD

**Issue by fsakhtari** [privefl/bigsnpr#110] opened 2020-07-10 21:06 UTC
Hello Florian,
Thank you for this package and the ldpred2 tutorial (https://privefl.github.io/bigsnpr/articles/LDpred2.html), which is very helpful.
I've been diligently following the ldpred2 tutorial to do PRS. Could you help me with a few questions:
I'm using the 1000G_phase1 data as the LDref panel + validation data and external summary statistics from a T2D meta-analysis. I'm running ldpred2 per chromosome. 

1. In my results, the adjusted beta values from snp_ldpred2_grid() are NAs for certain parameter combinations. I used the h2 estimate from snp_ldsc2() as shown in the tutorial and the same p_seq as in the tutorial. Is this expected ? Is it because for those parameter values, the adjusted betas could not be computed. How do I debug this to ensure that something isn't wrong + pick different p_seq values? A related question is what is the recommendation on choosing the values for the Grid of models and how to verify that the hyperparameter grid chosen leads to convergence, i.e. the next sequence won't lead to a significantly better result?

2. After doing  <_big_univLogReg(as_FBM(pred_grid[ind.val, ]), y[ind.val])_> from the tutorial, I want to use the model to predict y and then do AUC(y_pred, y_actual). I couldn't find a function to do that and big_univLogReg doesn't return the model specifications (intercept, etc.) for me to compute y_pred. Am I missing something or should I just use regular glm to do this?
The tutorial has <_AUCBoot(pred_nosp, y[ind.test])_>, but pred_nosp are the PRS values not the predicted phenotypes which is what I want to use to compute AUC. I don't quite understand how pred_no_sp is used here instead of y_pred? - are the pred_no_sp values scaled to be between 0&1?

3. The ldpred2 paper (bioarxiv) and the tutorial mention running ldpred2 per chromosome, scaling and combining results. I don't understand how the scaling needs to be done? How would we scale the "best" PRS for each chromosome before summing it all up? and also why do the PRSes need to be scaled ?

Hope you are staying safe and Thank you for your time in advance,
Farida Akhtari

**Comment by privefl** [comment] 2020-07-10 21:56
1. Are you using an old version of bigsnpr? Before, I just returned NAs when the model diverged. I have dropped this since.

2. `big_univLogReg()` is used to find the Z-scores to pick the best set of parameter. Then you use the score corresponding to this set of parameters. `pred_no_sp` is then the best PRS, not necessarily between 0 and 1 I think.

3. This "scaling" has been removed (see new version of preprint and tutorial) because it does not seem to be necessary. You can just sum up predictions from all 22 chromosome.

**Comment by fsakhtari** [comment] 2020-07-13 22:39
Thanks for the super-quick response, Florian.
1. I just updated to bigsnpr_1.4.5 from the master branch at privefl/bigsnpr. I'm still seeing NAs in the beta matrix. The df_beta does not contain any NAs, neither does the correlation matrix, corr0, from  snp_cor(). I've attached a snippet of 
[betagrid_chr17.txt](https://github.com/privefl/bigsnpr/files/4915519/betagrid_chr17.txt)
 - the beta_grid from snp_ldpred2_grid() for chr17, as an example. 
What output can I look at to debug this further?

#2 & #3 - Sounds good. I will do as you suggest here.

4. Sorry about piling on another question here: The tutorial states the following in the Automatic model - "and could keep only the ones that looks good.. (e.g. see code of paper)". Could you elaborate on what this means? I couldn't find anything in the bioarxiv draft of the paper regarding this.

**Comment by privefl** [comment] 2020-07-14 08:37
1/ This may be caused by some major divergence of the Gibbs sampler. This might reveal some problems with the sumstats. Have you performed the quality control recommended in LDpred2?
Also, it might be that the parameters are very different from the "true" ones. What p are failing? Is it much different from what auto reports?

4/ This refers to this code: https://github.com/privefl/paper-ldpred2/blob/master/code/run-ldpred2.R#L108 and is now explained at the end of Section "New LDpred2 models".

**Comment by fsakhtari** [comment] 2020-07-14 21:41
Thanks, Florian. 
I do the QC for summary statistics as specified in LDpred1 for the LD ref panel - maf filtering, variant pruning and unrelated individuals. I do the snp_match() for the summary statistics to only keep variants that match with the LD ref panel/validation data (after QC) and also match alleles. I haven't done the QC specified here yet - https://github.com/privefl/paper-ldpred2/blob/master/paper/paper-ldpred2-supp.pdf, (will be adding it to my code soon), since that is comparing with the validation data. However, if the problem was with specific variants, then only those would be NA, right?  In my case, all betas are NAs for specific values of the parameter grid.
I haven't run auto yet, will do that and compare p. I'm in training this week, so may take a little longer to try this and report back.

Different p are failing for different chromosomes.  For example, for chromosome 17:
"All adjusted beta values in 'beta_grid' are 'NA' for the following parameter grid combinations:"
 [1] "1"  "2"  "3"  "4"  "5"  "18" "19" "20" "21" "22" "23" "35" "36" "37" "38"
[16] "39" "40" "41" "52" "53" "54" "55" "56" "69" "70" "71" "72" "73" "74" "86"
[31] "87" "88" "89" "90" "91" "92"

where the param grid is :
[1] "Parameter grid:"
          p     h2 sparse
1   0.00010 0.0048  FALSE
2   0.00018 0.0048  FALSE
3   0.00032 0.0048  FALSE
4   0.00056 0.0048  FALSE
5   0.00100 0.0048  FALSE
6   0.00180 0.0048  FALSE
7   0.00320 0.0048  FALSE
8   0.00560 0.0048  FALSE
9   0.01000 0.0048  FALSE
10  0.01800 0.0048  FALSE
11  0.03200 0.0048  FALSE
12  0.05600 0.0048  FALSE
13  0.10000 0.0048  FALSE
14  0.18000 0.0048  FALSE
15  0.32000 0.0048  FALSE
16  0.56000 0.0048  FALSE
17  1.00000 0.0048  FALSE
18  0.00010 0.0069  FALSE
19  0.00018 0.0069  FALSE
20  0.00032 0.0069  FALSE
21  0.00056 0.0069  FALSE
22  0.00100 0.0069  FALSE
23  0.00180 0.0069  FALSE
24  0.00320 0.0069  FALSE
25  0.00560 0.0069  FALSE
26  0.01000 0.0069  FALSE
27  0.01800 0.0069  FALSE
28  0.03200 0.0069  FALSE
29  0.05600 0.0069  FALSE
30  0.10000 0.0069  FALSE
31  0.18000 0.0069  FALSE
32  0.32000 0.0069  FALSE
33  0.56000 0.0069  FALSE
34  1.00000 0.0069  FALSE
35  0.00010 0.0096  FALSE
36  0.00018 0.0096  FALSE
37  0.00032 0.0096  FALSE
38  0.00056 0.0096  FALSE
39  0.00100 0.0096  FALSE
40  0.00180 0.0096  FALSE
41  0.00320 0.0096  FALSE
42  0.00560 0.0096  FALSE
43  0.01000 0.0096  FALSE
44  0.01800 0.0096  FALSE
45  0.03200 0.0096  FALSE
46  0.05600 0.0096  FALSE
47  0.10000 0.0096  FALSE
48  0.18000 0.0096  FALSE
49  0.32000 0.0096  FALSE
50  0.56000 0.0096  FALSE
51  1.00000 0.0096  FALSE
52  0.00010 0.0048   TRUE
53  0.00018 0.0048   TRUE
54  0.00032 0.0048   TRUE
55  0.00056 0.0048   TRUE
56  0.00100 0.0048   TRUE
57  0.00180 0.0048   TRUE
58  0.00320 0.0048   TRUE
59  0.00560 0.0048   TRUE
60  0.01000 0.0048   TRUE
61  0.01800 0.0048   TRUE
62  0.03200 0.0048   TRUE
63  0.05600 0.0048   TRUE
64  0.10000 0.0048   TRUE
65  0.18000 0.0048   TRUE
66  0.32000 0.0048   TRUE
67  0.56000 0.0048   TRUE
68  1.00000 0.0048   TRUE
69  0.00010 0.0069   TRUE
70  0.00018 0.0069   TRUE
71  0.00032 0.0069   TRUE
72  0.00056 0.0069   TRUE
73  0.00100 0.0069   TRUE
74  0.00180 0.0069   TRUE
75  0.00320 0.0069   TRUE
76  0.00560 0.0069   TRUE
77  0.01000 0.0069   TRUE
78  0.01800 0.0069   TRUE
79  0.03200 0.0069   TRUE
80  0.05600 0.0069   TRUE
81  0.10000 0.0069   TRUE
82  0.18000 0.0069   TRUE
83  0.32000 0.0069   TRUE
84  0.56000 0.0069   TRUE
85  1.00000 0.0069   TRUE
86  0.00010 0.0096   TRUE
87  0.00018 0.0096   TRUE
88  0.00032 0.0096   TRUE
89  0.00056 0.0096   TRUE
90  0.00100 0.0096   TRUE
91  0.00180 0.0096   TRUE
92  0.00320 0.0096   TRUE
93  0.00560 0.0096   TRUE
94  0.01000 0.0096   TRUE
95  0.01800 0.0096   TRUE
96  0.03200 0.0096   TRUE
97  0.05600 0.0096   TRUE
98  0.10000 0.0096   TRUE
99  0.18000 0.0096   TRUE
100 0.32000 0.0096   TRUE
101 0.56000 0.0096   TRUE
102 1.00000 0.0096   TRUE

**Comment by privefl** [comment] 2020-07-15 06:00
Ok, so very small p are failing. Might just be that.

If some variants are bad, the errors will propagate within the Gibbs sampler. This is not very robust, but we have not yet find a way to make it more robust (except the quality control mentioned).

**Comment by PradoVarathan** [comment] 2020-07-19 15:06
Hi Florian! 
I have the similar issue now, after I did the QC as recommended in the supplementary information. Even after that, I still get NaN values in beta_grid (for a few) and beta_auto. Should I vary the p values accordingly?

**Comment by privefl** [comment] 2020-07-19 15:54
I mean, at the end, you just pick the values that works, so if only a few of them are bad, is it really a problem?

**Comment by PradoVarathan** [comment] 2020-07-19 19:26
I only have about 8-10 of the p values working in grid while the auto doesnt seem to work. I am currently planning on choosing those few p values as you suggested.

Thank you. Hopefully there is a solution.

**Comment by privefl** [comment] 2020-07-19 19:37
Could you describe the sumstats you're using?

**Comment by PradoVarathan** [comment] 2020-07-19 19:54
This is the sumstats I am currently using:
'data.frame':	7481590 obs. of  9 variables:
 $ rsid   : chr  "rs10" "rs10000008" "rs10000011" "rs10000014" ...
 $ a0     : chr  "A" "T" "T" "T" ...
 $ a1     : chr  "C" "C" "C" "C" ...
 $ beta   : num  -0.0026 0.0701 -0.0209 0.0007 0.0713 ...
 $ beta_se: num  0.0363 0.0681 0.035 0.0161 0.052 0.0231 0.0153 0.0588 0.0617 0.0306 ...
 $ p      : num  0.943 0.303 0.55 0.967 0.17 ...
 $ chr    : int  7 4 4 4 4 4 4 4 4 4 ...
 $ pos    : int  92383888 172776204 138223055 178447148 172019173 69548949 14172539 183288360 5349852 19510493 ...
 $ n_eff  : num  57148 57148 57148 57148 57148 ...
 - attr(*, "na.action")= 'omit' Named int  9 32 75 82 121 137 192 226 377 466 ...
  ..- attr(*, "names")= chr  "9" "32" "75" "82" ...

**Comment by privefl** [comment] 2020-07-19 20:19
And after `snp_match()`? 
What trait is it? 
The LDSC heritability for each chromosome?

**Comment by PradoVarathan** [comment] 2020-07-19 20:34
I am using this as a test before doing the original analysis, and thus not sure about the trait. I have chosen chr 19 for the current analysis and ldsc is set at h2 value of 0.05058565

**Comment by fsakhtari** [comment] 2020-07-30 17:54
Hi Florian,
I'm back from training and other stuff and ran my code as per your suggestions. I ran ldpred2-auto on the same sets of data as before with fol. parameters:
h2_est = <from snp_ldsc2>, vec_p_init = seq_log(1e-4, 0.9, length.out=17)
The small p were failing/had NAs for the betas. For example:
str(multi_auto)
List of 17
 $ :List of 5
  ..$ beta_est   : num [1:41947] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
  ..$ p_est      : num 2.39e-05
  ..$ h2_est     : num NaN
  ..$ path_p_est : num [1:1500] 0.000103 0.000253 0.000338 0.000399 0.001091 ...
  ..$ path_h2_est: num [1:1500] 0.00334 0.00423 0.00587 0.0091 0.01318 ...
 $ :List of 5
  ..$ beta_est   : num [1:41947] -9.30e-07 -9.29e-07 5.43e-06 1.24e-05 7.85e-06 ...
  ..$ p_est      : num 0.36
  ..$ h2_est     : num 0.000208
  ..$ path_p_est : num [1:1500] 0.000222 0.000407 0.000881 0.002419 0.002867 ...
  ..$ path_h2_est: num [1:1500] 0.00451 0.00722 0.01179 0.0207 0.02248 ...
This was seen consistently across all chromosomes.
I re-ran ldpred2-auto with vec_p_init = seq_log(1e-2, 0.9, length.out=17) and did not see any failures.
Conclusion: As you mentioned, very small p (rho values) are failing for my set of data.

Since I will be using ldpred2 for 10 different traits/summary statistics and I do want to use sparse as well, my plan is to do the fol. as per the recommendation in your paper:
1. Run ldpred2-auto to get valid/non-failing p and h2 estimates.
2. Build table of params using p & h2 values from (1) + sparse = T/F.
3. Run ldpred2 with table from (2).

I'm assuming that I can just use the p & h pairs with sparse=T/F from (1) above and not have to build a grid of p & h2 with every combination of p with every h2 or step through the range of p and h2, since ldpred2-auto has already iterated through these.

**Comment by privefl** [comment] 2020-07-30 18:02
Yes, seems like a good idea. But what do you want to rerun it with sparse=FALSE also?

I should probably code the option to have sparse=TRUE in auto, but I don't know how much people would be interested in this.

**Comment by fsakhtari** [comment] 2020-07-30 18:26
Sure, I can leave out sparse=FALSE and use those beta values from ldpred2-auto.
Yes, please. I vote +1 for ldred2-auto with sparse option (both T/F). I'd be using it right away 👍

**Comment by privefl** [comment] 2020-07-30 18:30
I'll see if I have time to work on this tomorrow. Shouldn't be too hard?

**Comment by fsakhtari** [comment] 2020-07-30 18:37
Cool! That would be awesome. Thanks so much, Florian!!

**Comment by privefl** [comment] 2020-07-31 09:27
You can now try using `sparse = TRUE` in `snp_ldpred2_auto()`.
You'll need the latest GitHub version of {bigsnpr}.

**Comment by fsakhtari** [comment] 2020-07-31 18:46
I'm using the sparse option in snp_ldpred2_auto and get the sparse and non-sparse betas in one go:
List of 17
 $ :List of 6
  ..$ beta_est       : num [1:24848] -1.42e-06 -1.42e-06 -1.43e-06 7.03e-06 3.26e-06 ...
  ..$ p_est          : num 0.0619
  ..$ h2_est         : num 0.000181
  ..$ path_p_est     : num [1:1500] 0.0106 0.0106 0.0102 0.0117 0.0107 ...
  ..$ path_h2_est    : num [1:1500] 0.00428 0.00461 0.00459 0.00534 0.00506 ...
  ..$ beta_est_sparse: num [1:24848] 0.00 0.00 0.00 7.08e-06 3.28e-06 ...
 $ :List of 6
  ..$ beta_est       : num [1:24848] -1.11e-06 -1.11e-06 -1.10e-06 5.47e-06 2.54e-06 ...
  ..$ p_est          : num 0.0622
  ..$ h2_est         : num 0.000141
  ..$ path_p_est     : num [1:1500] 0.0165 0.0165 0.0186 0.0179 0.0184 ...
  ..$ path_h2_est    : num [1:1500] 0.00376 0.0039 0.00397 0.00406 0.00405 ...
  ..$ beta_est_sparse: num [1:24848] 0.00 0.00 0.00 5.50e-06 2.55e-06 ...
 ......

Thanks so much Florian for doing this so quickly. I really appreciate it.

**Comment by privefl** [comment] 2020-07-31 19:38
You're welcome.

Please close the issue if there is nothing else.

**Closed** 2020-07-31 22:11 UTC

**Comment by privefl** [comment] 2020-10-03 10:13
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
